title: Ramesh Boopathi
email: sanjai.ramesh@gmail.com
description: >-
  Staff / Principal Software Engineer | Distributed Systems | Payments | AWS | Java

baseurl: ""
url: "https://sanjairamesh.github.io"

theme: minima

author:
  name: Ramesh Boopathi

minima:
  skin: classic

linkedin_username: ramesh-boopathi-7a840130
github_username: SanjaiRamesh

markdown: kramdown
highlighter: rouge
show_excerpts: true

header_pages:
  - projects.md
  - architecture.md

collections:
  projects:
    output: true
    permalink: /projects/:name/
  architecture:
    output: true
    permalink: /architecture/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: page
  - scope:
      path: ""
      type: "architecture"
    values:
      layout: page

plugins:
  - jekyll-feed
  - jekyll-seo-tag